"use client";
import './globals.css'
// import { Inter } from 'next/font/google'
import { Lato } from 'next/font/google'

import { lightTheme } from "./src/themes/lightTheme";
import { ThemeProvider, CssBaseline } from "@mui/material";

// const inter = Inter({ subsets: ['latin'] })
const lato = Lato({
  weight: ['300', '400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={lightTheme}>
        <CssBaseline />
          <body className={lato.className}>{children}</body>
      </ThemeProvider>
    </html>
  )
}
